# Use the official Node.js runtime as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port the dev server runs on
EXPOSE 5173

# The source code will be mounted as a volume from the host
# Start the Vite development server
CMD ["npm", "run", "build","&&","npm","run","dev", "--", "--host", "0.0.0.0", "--port", "5173"]
