# Use the official Node.js runtime as the base image
FROM node:20

WORKDIR /app

# Install PostgreSQL client dependencies (needed for sequelize) and nodemon
RUN apt-get update && apt-get install -y postgresql-client && npm install -g nodemon

EXPOSE 4000

# Install dependencies and run migrations before starting development server
CMD ["sh", "-c", "npm install && npx sequelize-cli db:migrate && nodemon index.js"]
